// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOB_Msc_1t48VgLOLemWw5NR9xN5GpD6s',
    appId: '1:419147297722:web:5f301e3bc0f6d0589f2383',
    messagingSenderId: '419147297722',
    projectId: 'fall-detection-system-de918',
    authDomain: 'fall-detection-system-de918.firebaseapp.com',
    storageBucket: 'fall-detection-system-de918.firebasestorage.app',
    measurementId: 'G-16GNQC9CEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-1XfxtYmwK8ahFezQbVzNn2HvE_tDNEw',
    appId: '1:419147297722:android:f9a6023ce5a070989f2383',
    messagingSenderId: '419147297722',
    projectId: 'fall-detection-system-de918',
    storageBucket: 'fall-detection-system-de918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWzK47YEzksDFeq2jU_pOn6XIX5R937yE',
    appId: '1:419147297722:ios:03ea4d2f6cddee999f2383',
    messagingSenderId: '419147297722',
    projectId: 'fall-detection-system-de918',
    storageBucket: 'fall-detection-system-de918.firebasestorage.app',
    iosBundleId: 'com.example.fallDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWzK47YEzksDFeq2jU_pOn6XIX5R937yE',
    appId: '1:419147297722:ios:c779566250cc5e589f2383',
    messagingSenderId: '419147297722',
    projectId: 'fall-detection-system-de918',
    storageBucket: 'fall-detection-system-de918.firebasestorage.app',
    iosBundleId: 'com.example.fall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOB_Msc_1t48VgLOLemWw5NR9xN5GpD6s',
    appId: '1:419147297722:web:c5c835c32a928e149f2383',
    messagingSenderId: '419147297722',
    projectId: 'fall-detection-system-de918',
    authDomain: 'fall-detection-system-de918.firebaseapp.com',
    storageBucket: 'fall-detection-system-de918.firebasestorage.app',
    measurementId: 'G-K3XHBDXT5W',
  );
}